version: '3'

services:

  db:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci

  www:
    build: .
    ports:
     - 127.0.0.1:8000:8000
    depends_on:
     - "db"
    restart: always
    volumes:
     - .:/usr/src/app
